### ISSUE TITLE
Filtriranje korisnika 

### ISSUE THREAD

**Issue by SlitYahoo** [cicnavi/wp-aaieduhr-auth#1]
Pozdrav, 
 je li moguće dobiti opciju "Filtriranje" i npr "Izuzetak" u vašem dodatku? Konkretno, moja srednja škola u kojoj sam djelatnik želi preći na Wordpress ali bismo zadržali mogućnost prijave putem AAIEduHR računa. Srednje škole, kako stvari sada izgledaju, nemaju specifične ili jedinstvene oblasti pa smo prepušteni da se bilo tko registrira na našu stranicu. No, kada bismo imali opciju Filtriranje po npr. Povezanost s ustanovom (hrEduPersonAffiliation) i filtriranje po Oznaci matične ustanove (hrEduPersonHomeOrg), mogli bismo dopustiti logiranje samo djelatnicima specifične škole. Opcija Izuzetak bila bi dobra ako bismo npr. nekog učenika ili učenike ovlastili za objavljivanje tekstova na školskoj stranici ili podstranici. 
Unaprijed hvala.

**Comment by cicnavi** [comment]
Marked as TODO, should implement in case of free time.
