### ISSUE TITLE
Logiranje i za programere web stranice

### ISSUE THREAD

**Issue by Krunoslav7** [cicnavi/wp-aaieduhr-auth#2]
Poštovani,

može li se uz AAI logiranje, omogućiti i standardno logiranje putem WP korisničkog imena i lozinke? Da se mogu logirati i programeri koji su izradili web stranicu

**Comment by cicnavi** [comment]
Provjerit ću na koji način to ostvariti.
-- 

Marko Ivančić
https://markoivancic.from.hr

**Comment by cicnavi** [comment]
Pustio sam novu verziju plugina.

U pluginu sada postoji nova opcija za postavljanje 'secret-a', pomoću kojeg se može privremeno onesposobiti AAI@EduHr autentikacija, pa molim isprobajte.

Iz changelog-a:
```
= 0.0.9 =
* Enable functionality to bypass AAI@EduHr authentication, so that a user can authenticate using regular WordPress
user / login form. This can be used in scenarios when a site maintainer does not have AAI@EduHr identity, but has
to be able to, for example, get to the site admin dashboard. To show WordPress login form, set the secret in
plugin settings (make sure that it is long-enough, hard-to-guess and with no chars which have special
meaning in URLs). Then, add 'aabs' query parameter in wp-login route, like:
/wp-login.php?aabs=some-secret
```
